package com.apnatransport.app;

import android.app.Activity;
import android.content.Intent;
import android.net.Uri;
import android.os.Bundle;
import android.provider.Settings;

// Capacitor equivalent of twa/patch-project.js's SettingsBridgeActivity for
// the old TWA build -- ported here verbatim (same logic, same package,
// same custom intent action) rather than regenerated by a CI script,
// since this Android project is committed directly and only needs this
// added once. See that file's header comment for the full "why": Chrome
// deliberately blocks web content from firing "android.settings.*"
// intents itself (an anti-phishing measure, confirmed on a real device),
// but this app's own native code has no such restriction on calling a
// system Settings API on itself. The web side reaches this Activity via
// a custom, app-specific intent action (not a system "android.settings.*"
// one) that Chrome/the WebView have no reason to block -- see
// androidSettingsBridgeUrl in src/App.jsx.
public class SettingsBridgeActivity extends Activity {
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        String target = getIntent().getStringExtra("target");
        Intent settingsIntent;
        if ("notifications".equals(target)) {
            settingsIntent = new Intent(Settings.ACTION_APP_NOTIFICATION_SETTINGS);
            settingsIntent.putExtra(Settings.EXTRA_APP_PACKAGE, getPackageName());
        } else {
            settingsIntent = new Intent(Settings.ACTION_APPLICATION_DETAILS_SETTINGS);
            settingsIntent.setData(Uri.fromParts("package", getPackageName(), null));
        }
        settingsIntent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
        if (settingsIntent.resolveActivity(getPackageManager()) != null) {
            startActivity(settingsIntent);
        }
        finish();
    }
}
